# Generated by Django 2.1.2 on 2018-11-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181027_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scheduler',
        ),
    ]
