# Generated by Django 2.1.2 on 2018-11-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
