# Generated by Django 2.1.2 on 2018-11-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
