# Generated by Django 3.0.4 on 2020-03-18 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='USER_WITH_NONAME', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=32)),
                ('second_name', models.CharField(default=None, max_length=32, null=True)),
                ('surname', models.CharField(default=None, max_length=64)),
                ('whenCreated', models.DateField(default=datetime.date.today)),
                ('student', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
