# Generated by Django 3.0.4 on 2020-03-18 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('numberOfBuilding', models.CharField(max_length=8)),
                ('postalCode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('degree', models.CharField(choices=[('1st', 'bachelor'), ('2nd', 'master'), ('only-master', 'only-master')], default='1st', max_length=12)),
                ('howManySemesters', models.IntegerField(default=0)),
                ('type', models.CharField(default='full-time', max_length=32)),
                ('whenDoesItStarts', models.CharField(choices=[('S', 'summer'), ('W', 'winter')], default='W', max_length=1)),
                ('faculty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('semester', models.IntegerField(default=1)),
                ('fieldOfStudy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.FieldOfStudy')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], default=None, max_length=3, null=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professor_to_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('semester', models.IntegerField(default=None)),
                ('lecture_hours', models.IntegerField(default=None, null=True)),
                ('laboratory_hours', models.IntegerField(default=None, null=True)),
                ('fieldOfStudy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.FieldOfStudy')),
                ('teachers', models.ManyToManyField(to='entities.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_to_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semester', models.IntegerField(default=1)),
                ('indexNumber', models.IntegerField(default=1, unique=True)),
                ('isFinished', models.BooleanField(default=False)),
                ('fieldOfStudy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.FieldOfStudy')),
                ('plan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], default=None, max_length=3, null=True)),
                ('whenStart', models.TimeField(default=None, null=True)),
                ('whenFinnish', models.TimeField(default=None, null=True)),
                ('dayOfWeek', models.IntegerField(default=None, null=True)),
                ('how_long', models.IntegerField(default=None, null=True)),
                ('plan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Plan')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Room')),
                ('subject', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Subject')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Teacher')),
            ],
        ),
    ]
