# Generated by Django 2.1.2 on 2018-11-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20181027_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fieldOfStudy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.FieldOfStudy'),
        ),
    ]
