# Generated by Django 2.1.2 on 2018-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_scheduledsubject_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsubject',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=True, to='entities.Subject'),
        ),
    ]
