# Generated by Django 2.1.2 on 2018-11-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20181117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(null=True, on_delete=True, to='entities.Building'),
        ),
        migrations.AlterField(
            model_name='scheduledsubject',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=True, to='entities.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=True, to='entities.Plan'),
        ),
    ]
