# Generated by Django 2.1.2 on 2018-11-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20181118_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='yearOfStudy',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='yearOfStudy',
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='degree',
            field=models.CharField(choices=[('1st', 'bachelor'), ('2nd', 'master'), ('only-master', 'only-master')], default='1st', max_length=12),
        ),
    ]
