# Generated by Django 2.1.2 on 2018-11-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20181118_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='howManySemesters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='type',
            field=models.CharField(default='full-time', max_length=32),
        ),
        migrations.AlterField(
            model_name='scheduledsubject',
            name='dayOfWeek',
            field=models.IntegerField(default=None),
        ),
    ]
