# Generated by Django 2.1.2 on 2018-11-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20181119_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.AddField(
            model_name='scheduledsubject',
            name='how_long',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='subject',
            name='laboratory_hours',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture_hours',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
