# Generated by Django 2.1.2 on 2018-11-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20181124_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsubject',
            name='how_long',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
