# Generated by Django 2.1.2 on 2018-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_auto_20181124_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
