# Generated by Django 2.1.2 on 2018-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_plan_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsubject',
            name='dayOfWeek',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledsubject',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=True, to='entities.Subject'),
        ),
        migrations.AlterField(
            model_name='scheduledsubject',
            name='whenFinnish',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledsubject',
            name='whenStart',
            field=models.TimeField(default=None, null=True),
        ),
    ]
