# Generated by Django 2.1.2 on 2018-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20181124_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsubject',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=True, to='entities.Room'),
        ),
    ]
