# Generated by Django 2.1.2 on 2018-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20181124_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsubject',
            name='type',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], default=None, max_length=3, null=True),
        ),
    ]
