# Generated by Django 2.1.2 on 2018-11-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_scheduledsubject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], default=None, max_length=3, null=True),
        ),
    ]
