# Generated by Django 2.1.2 on 2019-03-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='whenDoesItStarts',
            field=models.CharField(choices=[('W', 'winter'), ('S', 'summer')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='indexNumber',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
