# Generated by Django 2.2.1 on 2019-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0020_auto_20190310_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
